# Generated by Django 2.0.7 on 2018-08-02 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appuser', '0002_fans_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='friends',
            name='friend_id',
            field=models.IntegerField(default=1),
        ),
    ]
