# Generated by Django 2.0.7 on 2018-08-05 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appuser', '0005_auto_20180805_0913'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fans', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fan', to='appuser.Profile')),
                ('user_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appuser.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friends', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend', to='appuser.Profile')),
                ('user_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appuser.Profile')),
            ],
        ),
    ]
