# Generated by Django 2.0.7 on 2018-10-23 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='zip_code',
            field=models.CharField(max_length=6, null=True, verbose_name='邮政编码'),
        ),
    ]
