# Generated by Django 2.0.7 on 2018-10-26 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20181026_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='order_status',
            field=models.SmallIntegerField(choices=[(3, '待收货'), (5, '已完成'), (2, '待发货'), (1, '待支付'), (4, '待评价')], default=1, verbose_name='支付状态'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='pay_method',
            field=models.SmallIntegerField(choices=[(3, '支付宝'), (4, '银联支付'), (1, '货到付款'), (2, '微信支付')], default=3, verbose_name='支付方式'),
        ),
    ]
